#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only
"""Refuse to let data files into this project's tree.

Usage, from the repository root:

    # staged files, from pre-commit
    uv run python crony-eu/scripts/check_no_data.py FILE [FILE ...]
    # every tracked file under the guarded tree (CI, crony doctor)
    uv run python crony-eu/scripts/check_no_data.py --all

Exit status 1 prints every offending path with the reason; 2 means git was
unavailable. The rules are blunt on purpose. Fixtures are generated by Python
code, so no legitimate file here needs a data format.

**It guards a subtree, not the whole repository**, and the subtree is the
directory holding this script's parent, so the answer follows the script rather
than being configured. Today that is `crony-eu/`. The reason is the handover
(ADR-0014 in the other series): this repository also contains Serenata Europa,
whose tracked `data/sample/` holds six synthetic TED notices as XML. Those are a
legitimate test fixture under that project's rules and would trip every rule
below. When Crony moves to the repository root, the derivation keeps working and
the guarded tree becomes everything.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from collections.abc import Iterable, Sequence
from pathlib import Path

# Checked against the last suffix only, so templates such as network.html.j2 pass
# while data.csv.gz is still caught by ".gz".
BLOCKED_SUFFIXES: frozenset[str] = frozenset(
    {
        ".parquet",
        ".arrow",
        ".feather",
        ".csv",
        ".tsv",
        ".json",
        ".jsonl",
        ".ndjson",
        ".xml",
        ".xls",
        ".xlsx",
        ".ods",
        ".duckdb",
        ".db",
        ".sqlite",
        ".sqlite3",
        ".wal",
        ".zip",
        ".gz",
        ".bz2",
        ".xz",
        ".zst",
        ".7z",
        ".tar",
        ".pdf",
        ".html",
        ".htm",
        ".ipynb",
    }
)

# Top-level directories that would mean a data directory was created inside the repo.
FORBIDDEN_TOP_DIRS: frozenset[str] = frozenset(
    {"data", "raw", "staged", "matched", "flags", "cases", "output", "outputs"}
)

# Exact paths allowed despite a blocked suffix. Every entry is a reviewed code change.
ALLOWED_PATHS: frozenset[str] = frozenset(
    {
        ".vscode/settings.json",
        ".vscode/extensions.json",
    }
)

MAX_BYTES = 256 * 1024

# Exact paths allowed to exceed MAX_BYTES. The vendored vis-network build used to
# be here; ADR-0006 replaced it with a server-rendered SVG, so nothing large is
# expected in this tree any more.
ALLOWED_LARGE: frozenset[str] = frozenset({"uv.lock"})


def repo_root() -> Path:
    """Repository root according to git, or the current directory outside a checkout."""
    try:
        out = subprocess.run(
            ["git", "rev-parse", "--show-toplevel"],
            check=True,
            capture_output=True,
            text=True,
        ).stdout.strip()
    except (OSError, subprocess.CalledProcessError):
        return Path.cwd()
    return Path(out)


def guarded_tree(root: Path) -> str:
    """The subtree this script governs, relative to the repository root.

    Derived from where the script sits rather than configured, so moving the
    project moves the guard with it. Returns "" when the script's project is
    the repository, which is the state this is heading towards.
    """
    project = Path(__file__).resolve().parent.parent
    try:
        return project.relative_to(root.resolve()).as_posix()
    except ValueError:
        # The script was copied somewhere outside the checkout. Guard
        # everything rather than nothing.
        return ""


def within(path: str, tree: str) -> bool:
    return not tree or path == tree or path.startswith(f"{tree}/")


def tracked_files(root: Path) -> list[str]:
    """Every tracked file under the guarded tree, as POSIX paths from the root."""
    out = subprocess.run(
        ["git", "ls-files", "-z"],
        check=True,
        capture_output=True,
        cwd=root,
    ).stdout
    tree = guarded_tree(root)
    return [p for p in out.decode("utf-8").split("\0") if p and within(p, tree)]


def check(paths: Iterable[str], root: Path) -> list[str]:
    """One message per violation; an empty list means the paths are clean.

    Paths arrive relative to the repository root, which is where pre-commit and
    CI both run. The rules are about the project's own tree, so the guarded
    prefix is stripped before they are applied: `crony-eu/raw/x.csv` has to read
    as a forbidden top-level `raw/`, not as a file under `crony-eu/`. Messages
    report the path as given, so it can be copied into a command.
    """
    tree = guarded_tree(root)
    problems: list[str] = []
    for raw in paths:
        posix = Path(raw).as_posix()
        if not within(posix, tree):
            continue

        inner = posix[len(tree) + 1 :] if tree else posix
        rel = Path(inner)

        if len(rel.parts) > 1 and rel.parts[0] in FORBIDDEN_TOP_DIRS:
            problems.append(
                f"{posix}: '{rel.parts[0]}/' looks like a data directory; "
                "data belongs in $CRONY_DATA_DIR, outside the repository"
            )
            continue

        suffix = rel.suffix.lower()
        if suffix in BLOCKED_SUFFIXES and inner not in ALLOWED_PATHS:
            problems.append(
                f"{posix}: '{suffix}' is a data format; "
                "build fixtures in Python instead"
            )
            continue

        full = Path(posix) if Path(posix).is_absolute() else root / posix
        if inner not in ALLOWED_LARGE and full.is_file():
            size = full.stat().st_size
            if size > MAX_BYTES:
                problems.append(
                    f"{posix}: {size} bytes, over the {MAX_BYTES}-byte limit"
                )

    return problems


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Refuse to let data files into the repository."
    )
    parser.add_argument(
        "paths", nargs="*", help="files to check (pre-commit passes staged files)"
    )
    parser.add_argument(
        "--all", action="store_true", help="check every file tracked by git"
    )
    args = parser.parse_args(argv)

    root = repo_root()
    if args.all:
        try:
            paths = tracked_files(root)
        except (OSError, subprocess.CalledProcessError) as exc:
            print(f"cannot list tracked files: {exc}", file=sys.stderr)
            return 2
    else:
        paths = list(args.paths)

    problems = check(paths, root)
    for message in problems:
        print(message, file=sys.stderr)
    if problems:
        print(
            f"\n{len(problems)} file(s) blocked. See CLAUDE.md, constraint 1.",
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
