#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Refuse to let data files into the repository.

Usage:

    # staged files, from pre-commit
    uv run python scripts/check_no_data.py FILE [FILE ...]
    # every tracked file (CI, doctor)
    uv run python scripts/check_no_data.py --all

Exit status 1 prints every offending path with the reason; 2 means git was
unavailable. The rules are blunt on purpose. Fixtures are generated by Python
code, so no legitimate file in this repository needs a data format.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from collections.abc import Iterable, Sequence
from pathlib import Path

# Checked against the last suffix only, so templates such as network.html.j2 pass
# while data.csv.gz is still caught by ".gz".
BLOCKED_SUFFIXES: frozenset[str] = frozenset(
    {
        ".parquet",
        ".arrow",
        ".feather",
        ".csv",
        ".tsv",
        ".json",
        ".jsonl",
        ".ndjson",
        ".xml",
        ".xls",
        ".xlsx",
        ".ods",
        ".duckdb",
        ".db",
        ".sqlite",
        ".sqlite3",
        ".wal",
        ".zip",
        ".gz",
        ".bz2",
        ".xz",
        ".zst",
        ".7z",
        ".tar",
        ".pdf",
        ".html",
        ".htm",
        ".ipynb",
    }
)

# Top-level directories that would mean a data directory was created inside the repo.
FORBIDDEN_TOP_DIRS: frozenset[str] = frozenset(
    {"data", "raw", "staged", "matched", "flags", "cases", "output", "outputs"}
)

# Exact paths allowed despite a blocked suffix. Every entry is a reviewed code change.
ALLOWED_PATHS: frozenset[str] = frozenset(
    {
        ".vscode/settings.json",
        ".vscode/extensions.json",
    }
)

MAX_BYTES = 256 * 1024

# Exact paths allowed to exceed MAX_BYTES.
ALLOWED_LARGE: frozenset[str] = frozenset(
    {
        "uv.lock",
        "src/crony_eu/export/assets/vis-network.min.js",
    }
)


def repo_root() -> Path:
    """Repository root according to git, or the current directory outside a checkout."""
    try:
        out = subprocess.run(
            ["git", "rev-parse", "--show-toplevel"],
            check=True,
            capture_output=True,
            text=True,
        ).stdout.strip()
    except (OSError, subprocess.CalledProcessError):
        return Path.cwd()
    return Path(out)


def tracked_files(root: Path) -> list[str]:
    """Every file tracked by git, as POSIX paths relative to the repository root."""
    out = subprocess.run(
        ["git", "ls-files", "-z"],
        check=True,
        capture_output=True,
        cwd=root,
    ).stdout
    return [p for p in out.decode("utf-8").split("\0") if p]


def check(paths: Iterable[str], root: Path) -> list[str]:
    """One message per violation; an empty list means the paths are clean."""
    problems: list[str] = []
    for raw in paths:
        rel = Path(raw)
        posix = rel.as_posix()

        if len(rel.parts) > 1 and rel.parts[0] in FORBIDDEN_TOP_DIRS:
            problems.append(
                f"{posix}: '{rel.parts[0]}/' looks like a data directory; "
                "data belongs in $CRONY_DATA_DIR, outside the repository"
            )
            continue

        suffix = rel.suffix.lower()
        if suffix in BLOCKED_SUFFIXES and posix not in ALLOWED_PATHS:
            problems.append(
                f"{posix}: '{suffix}' is a data format; "
                "build fixtures in Python instead"
            )
            continue

        full = rel if rel.is_absolute() else root / rel
        if posix not in ALLOWED_LARGE and full.is_file():
            size = full.stat().st_size
            if size > MAX_BYTES:
                problems.append(
                    f"{posix}: {size} bytes, over the {MAX_BYTES}-byte limit"
                )

    return problems


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Refuse to let data files into the repository."
    )
    parser.add_argument(
        "paths", nargs="*", help="files to check (pre-commit passes staged files)"
    )
    parser.add_argument(
        "--all", action="store_true", help="check every file tracked by git"
    )
    args = parser.parse_args(argv)

    root = repo_root()
    if args.all:
        try:
            paths = tracked_files(root)
        except (OSError, subprocess.CalledProcessError) as exc:
            print(f"cannot list tracked files: {exc}", file=sys.stderr)
            return 2
    else:
        paths = list(args.paths)

    problems = check(paths, root)
    for message in problems:
        print(message, file=sys.stderr)
    if problems:
        print(
            f"\n{len(problems)} file(s) blocked. See CLAUDE.md, constraint 1.",
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
